// src/react/MagicaretInput.tsx
import { forwardRef, useEffect, useRef } from 'react'
import { Magicaret } from '../Magicaret'
import type { MagicaretOptions } from '../types'

export interface MagicaretInputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'ref'> {
  magicaretOptions?: MagicaretOptions
}

export const MagicaretInput = forwardRef<HTMLInputElement, MagicaretInputProps>(
  ({ magicaretOptions = {}, ...props }, ref) => {
    const internalRef = useRef<HTMLInputElement | null>(null)
    const magicaretRef = useRef<Magicaret | null>(null)

    const setRefs = (node: HTMLInputElement | null) => {
      internalRef.current = node
      if (typeof ref === 'function') {
        ref(node)
      } else if (ref) {
        ref.current = node
      }
    }

    useEffect(() => {
      if (internalRef.current) {
        magicaretRef.current = new Magicaret(internalRef.current, magicaretOptions)
      }

      return () => {
        if (magicaretRef.current) {
          magicaretRef.current.destroy()
        }
      }
    }, [])

    useEffect(() => {
      if (magicaretRef.current) {
        magicaretRef.current.updateOptions(magicaretOptions)
      }
    }, [magicaretOptions])

    return <input ref={setRefs} {...props} />
  }
)

MagicaretInput.displayName = 'MagicaretInput'

// src/vue/MagicaretInput.vue
<template>
  <input ref="inputRef" v-bind="$attrs" />
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { Magicaret } from '../Magicaret'
import type { MagicaretOptions } from '../types'

interface Props {
  magicaretOptions?: MagicaretOptions
}

const props = withDefaults(defineProps<Props>(), {
  magicaretOptions: () => ({})
})

const inputRef = ref<HTMLInputElement | null>(null)
const magicaretRef = ref<Magicaret | null>(null)

onMounted(() => {
  if (inputRef.value) {
    magicaretRef.value = new Magicaret(inputRef.value, props.magicaretOptions)
  }
})

onUnmounted(() => {
  if (magicaretRef.value) {
    magicaretRef.value.destroy()
  }
})

watch(
  () => props.magicaretOptions,
  (newOptions) => {
    if (magicaretRef.value) {
      magicaretRef.value.updateOptions(newOptions)
    }
  },
  { deep: true }
)
</script>
